// The README doubles as the crate documentation, which also makes every Rust
// example in it a doc test. Its examples need the default feature set.
#![cfg_attr(
    all(
        feature = "partial-row",
        feature = "pagination",
        feature = "repository-error",
        feature = "retry"
    ),
    doc = include_str!("../README.md")
)]

pub mod full_text_search;
pub mod pool;
pub mod projection;
pub mod query_builder;
pub mod types;

#[cfg(feature = "repository-error")]
pub mod errors;

#[cfg(feature = "retry")]
pub mod retry;
#[cfg(feature = "retry")]
pub use pgkit_derive::retry;

#[cfg(test)]
pub(crate) mod test_support;

#[cfg(all(feature = "partial-row", feature = "cursor-pagination"))]
pub use pgkit_derive::PgKit;

/// Re-exports for code generated by `#[derive(PgKit)]`, so callers
/// don't need these crates as direct dependencies. Not public API.
#[cfg(all(feature = "partial-row", feature = "cursor-pagination"))]
#[doc(hidden)]
pub mod __private {
    pub use serde;
    pub use serde_json;
    pub use sqlx;
    pub use strum;
}

#[cfg(feature = "partial-row")]
pub mod try_get_option;
#[cfg(feature = "partial-row")]
pub use try_get_option::try_get_option;

pub mod ordering;

#[cfg(any(feature = "offset-pagination", feature = "cursor-pagination"))]
pub mod pagination;
